import { AlertCircle, ArrowRight, CalendarDays, CheckCircle2, Lightbulb, Plus, Sparkles } from 'lucide-react';
import { useCallback, useEffect, useState, type ReactNode } from 'react';
import { useApp } from '../../app/AppContext';
import { Button, EmptyState, PageHeader, StatusPill } from '../../components/ui/ProductUI';
import { api } from '../../services/api';
import type { DashboardSnapshot, AttentionSignal } from '../../types/dashboard';
import { NewArrivalsSource } from '../sources/NewArrivalsSource';

export default function DashboardPage() {
  const { activeEntity, setActiveTab, setActiveCampaignId, newStudioSession } = useApp();
  const [dashboard, setDashboard] = useState<DashboardSnapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const workspaceId = activeEntity?.id ?? '';
  const load = useCallback(async () => { if (!workspaceId) return; setLoading(true); setError(''); try { setDashboard(await api.getDashboard(workspaceId)); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [workspaceId]);
  useEffect(() => { void load(); }, [load]);
  const navigate = (target: string) => { const [kind,id,section] = target.split(':'); if (kind === 'campaign') { setActiveCampaignId(id); if (section) sessionStorage.setItem('campaignDetailTab',section); setActiveTab('campaign-detail'); } else if (kind === 'library') setActiveTab('learn'); };
  const dismiss = async (id:string) => { await api.dismissAttentionSignal(id,workspaceId); await load(); };
  if (loading) return <div className="mos-page max-w-6xl"><Header name={activeEntity?.name}/><div className="space-y-3"><div className="mos-skeleton h-28"/><div className="mos-skeleton h-16"/><div className="mos-skeleton h-16"/></div></div>;
  if (!dashboard) return <div className="mos-page max-w-6xl"><Header name={activeEntity?.name}/>{/* We couldn&apos;t load your dashboard */}<EmptyState icon={<AlertCircle className="h-6 w-6"/>} title="We couldn't load your dashboard" description="Your work is still safe. Check the connection and try again." action={<Button variant="secondary" onClick={()=>void load()}>Try again</Button>}/>{import.meta.env.DEV && error && <p className="text-xs text-zinc-400">{error}</p>}</div>;
  const firstAction = dashboard.needsAttention[0] ?? dashboard.readyForYou[0]; const insight = dashboard.performance.highPerforming[0] ?? dashboard.performance.underperforming[0];
  return <div className="mos-page max-w-6xl"><Header name={activeEntity?.name} action={<Button onClick={()=>newStudioSession()}><Plus className="h-4 w-4"/> Create content</Button>}/>
    {firstAction ? <button type="button" onClick={()=>firstAction.actionTarget && navigate(firstAction.actionTarget)} className="group flex w-full items-center gap-5 rounded-2xl bg-zinc-950 px-6 py-5 text-left text-white transition hover:bg-zinc-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-950 focus-visible:ring-offset-2"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-white/10"><ArrowRight className="h-5 w-5"/></span><span className="min-w-0 flex-1"><span className="text-[10px] font-bold uppercase tracking-[.16em] text-zinc-400">Start here</span><span className="mt-1 block text-lg font-semibold tracking-tight">{humanTitle(firstAction.title)}</span><span className="mt-1 block text-sm text-zinc-300">{humanSummary(firstAction.summary)}</span></span><ArrowRight className="h-5 w-5 transition group-hover:translate-x-1"/></button> : <div className="flex items-center gap-4 rounded-2xl bg-emerald-50 px-6 py-5 text-emerald-950"><CheckCircle2 className="h-6 w-6"/><div><p className="font-semibold">You’re clear for now</p><p className="text-sm text-emerald-800">Nothing needs immediate attention.</p></div></div>}
    <div className="grid gap-10 lg:grid-cols-[1.3fr_.7fr]"><section><div className="mb-3 flex items-end justify-between"><div><p className="mos-eyebrow">Today’s work</p><h2 className="mt-1 text-xl font-semibold tracking-tight">What needs you</h2></div><StatusPill tone={dashboard.counts.needsAttention ? 'warning' : 'success'}>{dashboard.counts.needsAttention + dashboard.counts.readyForReview} items</StatusPill></div><div className="divide-y divide-zinc-200 border-y border-zinc-200">{[...dashboard.needsAttention.slice(1),...dashboard.readyForYou].slice(0,5).map(s=><Signal key={s.id} signal={s} onAction={navigate} onDismiss={dismiss}/>)}{dashboard.needsAttention.slice(1).length + dashboard.readyForYou.length === 0 && <p className="py-7 text-sm text-zinc-500">No other decisions are waiting.</p>}</div></section>
      <section><p className="mos-eyebrow">Coming next</p><h2 className="mt-1 text-xl font-semibold tracking-tight">On the calendar</h2><div className="mt-3 space-y-1">{dashboard.upcoming.slice(0,4).map(u=><button key={u.scheduleId} onClick={()=>setActiveTab('calendar')} className="flex w-full gap-3 rounded-xl px-2 py-3 text-left hover:bg-zinc-50"><CalendarDays className="mt-0.5 h-4 w-4 shrink-0 text-zinc-400"/><span><span className="block text-sm font-medium">{friendlyName(u.campaignName,u.contentKey)}</span><span className="mt-1 block text-xs text-zinc-500">{u.localDayLabel} · {u.localTimeLabel} · {titleCase(u.channel)}</span></span></button>)}{dashboard.upcoming.length===0&&<p className="mt-3 rounded-xl bg-zinc-50 p-4 text-sm text-zinc-500">Nothing scheduled yet. Create or approve content to begin planning the week.</p>}</div></section></div>
    {sectionHasContent(insight) && <section className="grid gap-5 border-t border-zinc-200 pt-7 md:grid-cols-[auto_1fr_auto]"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-700"><Lightbulb className="h-5 w-5"/></span><div><p className="mos-eyebrow">Useful learning</p><p className="mt-1 text-base font-semibold">{insight.campaignName}</p><p className="mt-1 text-sm leading-6 text-zinc-500">{insight.reasons?.[0] ?? `${insight.primaryKpi} is the clearest signal so far.`}</p></div><Button variant="quiet" onClick={()=>setActiveTab('learn')}>See what worked <ArrowRight className="h-4 w-4"/></Button></section>}
    {activeEntity?.name.trim().toLowerCase()==='worn label'&&<NewArrivalsSource/>}
    {dashboard.empty && <EmptyState icon={<Sparkles className="h-7 w-7"/>} title="Your marketing week starts here" description="Create a campaign and MarketingOS will guide it from idea to published work." action={<Button onClick={()=>newStudioSession()}>Create your first content</Button>}/>}</div>;
}
function Header({name,action}:{name?:string;action?:ReactNode}) { const day = new Intl.DateTimeFormat('en-NZ',{weekday:'long',day:'numeric',month:'long'}).format(new Date()); return <PageHeader eyebrow={`${day} · ${name ?? 'Your workspace'}`} title="What needs your attention today?" description="A calm view of the decisions, publishing work and useful signals that move your marketing forward." action={action}/>; }
function Signal({signal,onAction,onDismiss}:{signal:AttentionSignal;onAction:(s:string)=>void;onDismiss:(s:string)=>void}) { return <div className="group flex items-start gap-4 py-4"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${signal.severity==='CRITICAL'||signal.severity==='HIGH'?'bg-red-500':'bg-amber-500'}`}/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{humanTitle(signal.title)}</p>{signal.summary&&<p className="mt-1 text-sm leading-5 text-zinc-500">{humanSummary(signal.summary)}</p>}</div>{signal.dismissible&&<button onClick={()=>onDismiss(signal.id)} className="text-xs text-zinc-400 hover:text-zinc-700">Dismiss</button>}{signal.actionTarget&&<button onClick={()=>onAction(signal.actionTarget!)} className="flex items-center gap-1 text-xs font-semibold">{signal.actionLabel??'Open'} <ArrowRight className="h-3 w-3"/></button>}</div>; }
function humanTitle(value:string){return value.replace(/Campaign camp_[\w-]+/g,'Campaign').replace(/Publishing failed/i,'Needs publishing attention').replace(/Media issue/i,'Creative needs media');}
function humanSummary(value?:string){return (value??'').replace(/Publish outcome unknown — reconciliation required/i,"We’re not certain this published. Check the external post before taking action.").replace(/provider/gi,'connected platform');}
function friendlyName(campaign:string,key:string){if(!campaign.startsWith('Campaign camp_'))return campaign; return key.replaceAll('-',' ').replace(/\b\w/g,m=>m.toUpperCase());}
function titleCase(value:string){return value.toLowerCase().replace(/\b\w/g,m=>m.toUpperCase());}
function sectionHasContent<T>(value: T | null | undefined): value is T { return value !== null && value !== undefined; }
