import { ArrowRight, BookOpen, Lightbulb, Sparkles, TrendingDown, TrendingUp } from 'lucide-react';
import { useEffect, useState } from 'react';
import { useApp } from '../../app/AppContext';
import { Button, EmptyState, PageHeader, StatusPill } from '../../components/ui/ProductUI';
import { api } from '../../services/api';
import type { WorkspacePerformanceSummary, CampaignBlueprint } from '../../types';
import type { DashboardSnapshot } from '../../types/dashboard';

export default function LearnPage() {
  const { activeEntity, setActiveCampaignId, setActiveTab } = useApp();
  const [performance, setPerformance] = useState<WorkspacePerformanceSummary | null>(null); const [dashboard, setDashboard] = useState<DashboardSnapshot | null>(null); const [blueprints, setBlueprints] = useState<CampaignBlueprint[]>([]);
  useEffect(() => { if (!activeEntity) return; Promise.all([api.getPerformanceSummary(activeEntity.id), api.getDashboard(activeEntity.id), api.getBlueprints(activeEntity.id)]).then(([p,d,b])=>{setPerformance(p);setDashboard(d);setBlueprints(b);}).catch(()=>{}); }, [activeEntity]);
  const high = dashboard?.performance.highPerforming ?? []; const low = dashboard?.performance.underperforming ?? [];
  const openCampaign = (id:string) => { setActiveCampaignId(id); sessionStorage.setItem('campaignDetailTab','performance'); setActiveTab('campaign-detail'); };
  return <div className="mos-page max-w-6xl"><PageHeader eyebrow={`${activeEntity?.name ?? 'Brand'} intelligence`} title="What are we learning?" description="Useful conclusions from your campaigns, content and results—so the next decision gets easier." action={<Button variant="secondary" onClick={()=>setActiveTab('library')}><BookOpen className="h-4 w-4" /> History & blueprints</Button>} />
    {(high.length || low.length) ? <div className="grid gap-10 lg:grid-cols-2"><InsightList title="Worth repeating" icon={<TrendingUp className="h-4 w-4"/>} items={high} onOpen={openCampaign}/><InsightList title="Needs a different approach" icon={<TrendingDown className="h-4 w-4"/>} items={low} onOpen={openCampaign}/></div> : <EmptyState icon={<Lightbulb className="h-7 w-7"/>} title="Your learnings will build here" description="Publish and measure a campaign to see what worked, what needs changing, and what is worth repeating." action={<Button onClick={()=>setActiveTab('campaigns')}>Open campaigns</Button>} />}
    <section><div className="flex items-end justify-between"><div><p className="mos-eyebrow">Reusable knowledge</p><h2 className="mt-1 text-lg font-semibold tracking-tight">Blueprints and saved patterns</h2></div><StatusPill tone="info">{blueprints.length} saved</StatusPill></div>{blueprints.length ? <div className="mt-4 grid gap-4 md:grid-cols-2">{blueprints.slice(0,4).map(bp=><div key={bp.id} className="rounded-2xl bg-zinc-50 p-5"><Sparkles className="h-4 w-4"/><p className="mt-6 font-semibold">{bp.name}</p><p className="mt-2 text-sm leading-6 text-zinc-500">{bp.learnedWhy[0] ?? bp.description ?? 'A proven structure ready to adapt.'}</p></div>)}</div> : <p className="mt-4 border-t border-zinc-200 pt-4 text-sm text-zinc-500">Strong campaigns can be saved here as reusable blueprints.</p>}</section>
    {performance && <p className="text-xs text-zinc-400">Based on {performance.campaignsMeasured} measured {performance.campaignsMeasured === 1 ? 'campaign' : 'campaigns'} and the evidence currently available.</p>}</div>;
}
function InsightList({title,icon,items,onOpen}:{title:string;icon:React.ReactNode;items:DashboardSnapshot['performance']['highPerforming'];onOpen:(id:string)=>void}) { return <section><div className="flex items-center gap-2">{icon}<h2 className="text-lg font-semibold tracking-tight">{title}</h2></div><div className="mt-3 divide-y divide-zinc-200 border-y border-zinc-200">{items.map(item=><button key={item.campaignId} onClick={()=>onOpen(item.campaignId)} className="group flex w-full items-center gap-4 py-5 text-left"><span className="min-w-0 flex-1"><span className="block font-semibold">{item.campaignName}</span><span className="mt-1 block text-sm leading-6 text-zinc-500">{item.reasons?.[0] ?? `${item.primaryKpi} is the clearest signal so far.`}</span></span><ArrowRight className="h-4 w-4 text-zinc-400 group-hover:translate-x-1"/></button>)}</div></section>; }
